// packages/react/src/DayFlowCalendar.tsx
import {
  useRef,
  useEffect,
  useState,
  useMemo,
  type ReactNode,
  type FC,
} from 'react';
import { createPortal } from 'react-dom';
import {
  CalendarRenderer,
  type ICalendarApp,
  type CustomRendering,
  type UseCalendarAppReturn,
} from '@dayflow/core';

export interface DayFlowCalendarProps {
  calendar: ICalendarApp | UseCalendarAppReturn;
  /** Custom event content renderer (React) */
  eventContent?: (args: {
    event: any;
    isAllDay: boolean;
    isMobile: boolean;
  }) => ReactNode;
  /** Custom event detail panel content (React) */
  eventDetailContent?: (args: {
    event: any;
    position: any;
    onClose: () => void;
  }) => ReactNode;
  /** Custom event detail dialog (React) */
  eventDetailDialog?: (args: {
    event: any;
    isOpen: boolean;
    onClose: () => void;
    onEventUpdate: any;
    onEventDelete: any;
    isAllDay: boolean;
    app: any;
  }) => ReactNode;
  /** Custom calendar header content (React) */
  headerContent?: (args: any) => ReactNode;
  /** Custom create calendar dialog (React) */
  createCalendarDialog?: (args: {
    onClose: () => void;
    onCreate: (calendar: any) => void;
    colorPickerMode?: string;
  }) => ReactNode;
  /** Title bar slot (React) */
  titleBarSlot?:
    | ReactNode
    | ((context: {
        isCollapsed: boolean;
        toggleCollapsed: () => void;
      }) => ReactNode);
  /** Custom color picker renderer (React) */
  colorPicker?: (args: any) => ReactNode;
  /** Custom color picker wrapper renderer (React) */
  colorPickerWrapper?: (args: any) => ReactNode;
}

export const DayFlowCalendar: FC<DayFlowCalendarProps> = ({
  calendar,
  ...renderProps
}: DayFlowCalendarProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<CalendarRenderer | null>(null);
  const [customRenderings, setCustomRenderings] = useState<
    Map<string, CustomRendering>
  >(new Map());

  // Extract the underlying app instance
  const app = (calendar as any)?.app || calendar;

  useEffect(() => {
    if (!containerRef.current || !app) return;

    const renderer = new CalendarRenderer(app);
    rendererRef.current = renderer;
    renderer.mount(containerRef.current);

    const unsubscribe = renderer
      .getCustomRenderingStore()
      .subscribe(renderings => {
        // Create a new map to trigger re-render
        setCustomRenderings(new Map(renderings));
      });

    return () => {
      unsubscribe();
      renderer.unmount();
      rendererRef.current = null;
    };
  }, [app]);

  useEffect(() => {
    if (!rendererRef.current) return;
    const store = rendererRef.current.getCustomRenderingStore();
    const activeOverrides = Object.keys(renderProps).filter(
      key => (renderProps as any)[key] !== undefined
    );
    store.setOverrides(activeOverrides);
  }, [renderProps]);

  // Portals for custom content
  const portals = useMemo(() => {
    return Array.from(customRenderings.values()).map(
      (rendering: CustomRendering) => {
        const { id, containerEl, generatorName, generatorArgs } = rendering;

        // Look up the generator in renderProps
        const generator = (renderProps as any)[generatorName];

        if (!generator) {
          return null;
        }

        const content =
          typeof generator === 'function'
            ? generator(generatorArgs)
            : generator;

        return createPortal(content, containerEl, id);
      }
    );
  }, [customRenderings, renderProps]);

  return (
    <>
      <div ref={containerRef} className="df-calendar-wrapper" />
      {portals}
    </>
  );
};

// packages/svelte/src/DayFlowCalendar.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { 
    CalendarRenderer, 
    type ICalendarApp, 
    type UseCalendarAppReturn, 
    type CustomRendering 
  } from '@dayflow/core';

  export let calendar: ICalendarApp | UseCalendarAppReturn;
  
  // Custom renderers passed as props (Svelte components)
  export let eventContent: any = null;
  export let eventDetailContent: any = null;
  export let eventDetailDialog: any = null;
  export let headerContent: any = null;
  export let createCalendarDialog: any = null;
  export let titleBarSlot: any = null;
  export let colorPicker: any = null;
  export let colorPickerWrapper: any = null;

  let container: HTMLElement;
  let renderer: CalendarRenderer;
  let customRenderings: CustomRendering[] = [];
  let unsubscribe: () => void;

  $: app = (calendar as any).app || calendar;
  
  const renderProps: Record<string, any> = {
    eventContent,
    eventDetailContent,
    eventDetailDialog,
    headerContent,
    createCalendarDialog,
    titleBarSlot,
    colorPicker,
    colorPickerWrapper
  };

  onMount(() => {
    renderer = new CalendarRenderer(app);
    renderer.mount(container);

    unsubscribe = renderer.getCustomRenderingStore().subscribe((renderings) => {
      customRenderings = Array.from(renderings.values());
    });

    // Synchronize slot overrides
    const activeOverrides = Object.keys(renderProps).filter(key => renderProps[key] !== null);
    renderer.getCustomRenderingStore().setOverrides(activeOverrides);
  });

  onDestroy(() => {
    if (unsubscribe) unsubscribe();
    if (renderer) renderer.unmount();
  });

  function portal(node: HTMLElement, target: HTMLElement) {
    target.appendChild(node);
    return {
      destroy() {
        if (node.parentNode === target) {
          target.removeChild(node);
        }
      }
    };
  }
</script>

<div bind:this={container} class="df-calendar-wrapper"></div>

{#each customRenderings as rendering (rendering.id)}
  {@const Component = renderProps[rendering.generatorName]}
  {#if Component}
    <div use:portal={rendering.containerEl}>
      <svelte:component this={Component} {...rendering.generatorArgs} />
    </div>
  {/if}
{/each}
